version: 2.1
jobs:
  test-server:
    working_directory: ~/boilerplate-server-node
    docker:
      - image: circleci/node:12.16.2
        environment:
          JWT_SECRET: ${JWT_SECRET}
          NODE_ENV: test

      - image: circleci/postgres:12
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: goodpassword1$
          POSTGRES_DB: test_db

    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: install-packages
          command: 'npm install --no-audit'
      - run:
          name: run-audit
          command: 'npm audit --audit-level=moderate'
      - save_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: run-migrations
          command: 'npm run db:migrate-testdb'
      - run:
          name: run-unit-tests
          command: 'npm run test'
      - run:
          name: run-e2e-tests
          command: 'npm run test:e2e'
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: test_results

workflows:
  version: 2
  build_and_test:
    jobs:
      - test-server
